title: wgpu user stories
description: >-
  This little blog collects battle stories of `wgpu` users.
  It's a place anyone could share their progress with the community.
baseurl: "/stories"


#theme: jekyll-theme-tactile
theme: minima
plugins:
  - jekyll-feed

show_downloads: false
